// Farma Oborin Homepage — Shared Script
// Generated by UXMagic Copilot

document.addEventListener('DOMContentLoaded', function () {
  var mobileMenu = document.querySelector('#mobile-menu');
  var mobileMenuToggle = document.querySelector('.mobile-menu-toggle');
  var mobileMenuIcon = document.querySelector('.mobile-menu-icon');

  function closeMobileMenu() {
    if (!mobileMenu || !mobileMenuToggle || !mobileMenuIcon) return;
    mobileMenu.classList.add('hidden');
    mobileMenuToggle.setAttribute('aria-expanded', 'false');
    mobileMenuIcon.setAttribute('icon', 'lucide:menu');
  }

  if (mobileMenu && mobileMenuToggle && mobileMenuIcon) {
    mobileMenuToggle.addEventListener('click', function () {
      var isOpen = !mobileMenu.classList.contains('hidden');
      mobileMenu.classList.toggle('hidden', isOpen);
      mobileMenuToggle.setAttribute('aria-expanded', String(!isOpen));
      mobileMenuIcon.setAttribute('icon', isOpen ? 'lucide:menu' : 'lucide:x');
    });
  }

  // Smooth scroll for anchor links
  document.querySelectorAll('a[href^="#"]').forEach(function (anchor) {
    anchor.addEventListener('click', function (e) {
      var target = document.querySelector(this.getAttribute('href'));
      if (target) { e.preventDefault(); target.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
      closeMobileMenu();
    });
  });

  // Prevent default form submit
  document.querySelectorAll('form').forEach(function (form) {
    form.addEventListener('submit', function (e) { e.preventDefault(); });
  });


});

window.UIUtils = {
  toggleElement: function (selector) {
    var el = document.querySelector(selector);
    if (el) el.style.display = el.style.display === 'none' ? '' : 'none';
  },
};
