// Kovošrot Vašin Homepage Redesign — Shared Script
// Generated by UXMagic Copilot

document.addEventListener('DOMContentLoaded', function () {
  // Mobile navigation toggle
  var navToggle = document.getElementById('nav-toggle');
  var mobileNav = document.getElementById('mobile-nav');
  var iconMenu = document.getElementById('nav-icon-menu');
  var iconClose = document.getElementById('nav-icon-close');

  function setMobileNavOpen(isOpen) {
    if (!mobileNav || !navToggle) return;
    mobileNav.classList.toggle('hidden', !isOpen);
    navToggle.setAttribute('aria-expanded', String(isOpen));
    navToggle.setAttribute('aria-label', isOpen ? 'Zavrieť menu' : 'Otvoriť menu');
    if (iconMenu) iconMenu.classList.toggle('hidden', isOpen);
    if (iconClose) iconClose.classList.toggle('hidden', !isOpen);
  }

  if (navToggle && mobileNav) {
    navToggle.addEventListener('click', function () {
      setMobileNavOpen(mobileNav.classList.contains('hidden'));
    });

    mobileNav.querySelectorAll('a').forEach(function (link) {
      link.addEventListener('click', function () {
        setMobileNavOpen(false);
      });
    });
  }

  // Smooth scroll for anchor links
  document.querySelectorAll('a[href^="#"]').forEach(function (anchor) {
    anchor.addEventListener('click', function (e) {
      var target = document.querySelector(this.getAttribute('href'));
      if (target) { e.preventDefault(); target.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
    });
  });

  // Prevent default form submit
  document.querySelectorAll('form').forEach(function (form) {
    form.addEventListener('submit', function (e) { e.preventDefault(); });
  });


});

window.UIUtils = {
  toggleElement: function (selector) {
    var el = document.querySelector(selector);
    if (el) el.style.display = el.style.display === 'none' ? '' : 'none';
  },
};
